sudo: required

services:
  - docker
env:
  - IMAGE_NAME=msvrtan/code
script:
  - docker build -t $IMAGE_NAME:latest .
  - if [ $TRAVIS_TAG ]; then docker build -t $IMAGE_NAME:$TRAVIS_TAG . ; fi

after_success:
  - docker login -u="$REGISTRY_USER" -p="$REGISTRY_PASS"
  - if [ "$TRAVIS_TAG" ]; then docker push $IMAGE_NAME:$TRAVIS_TAG; fi
  - if [[ $TRAVIS_BRANCH = master ]]; then docker push $IMAGE_NAME:latest; fi
  - docker logout

  